module.exports =new Map([
    ['000', 'Success'],
    ['001', 'Unathorized API Key'],
    ['002', 'Unathorized source IP Address'],
    ['003', 'Invalid API Format'],
    ['004', 'Mandatory Attribute Missing'],
    ['009', 'Trunk Group in used'],
    ['401', 'Trunk Group Name Too Long or Format Incorrect'],
    ['402', 'Duplicated Trunk Group Name'],
    ['403', 'Trunk Group ID Must be Numeric'],
    ['404', 'Trunk Group ID Not Found in the System'],
    ['405', 'Nap Too Long or Format Incorrect'],
    ['406', 'Trunk Interface Must be "HGC" or "CUSTOMER"'],
    ['407', 'Trunk ID Must be Numeric'],
    ['408', 'Trunk ID Not Found in the System'],
    ['409', 'Exceed maximum Trunks in the Trunk Group'],
    ['411', 'Translation Profile ID Must be Numeric'],
    ['412', 'Translation Profile ID Not Found in the System'],
    ['413', 'Translation Profile Name Too Long or Format Incorrect'],
    ['414', 'Translation Profile Name Not Found in the System'],
    ['421', 'Customer Name Too Long or Format Incorrect'],
    ['422', 'Duplicated Customer Name'],
    ['423', 'Customer ID Must Numeric'],
    ['424', 'Customer ID Not Found in the System'],
    ['425', 'Sub Account Name Too Long or Format Incorrect'],
    ['426', 'Duplicated Sub Account Name'],
    ['427', 'Sub account tied to the customer ID'],
    ['428', 'User tied to the customer ID'],
    ['429', 'Sub Account ID Must be Numeric'],
    ['430', 'Sub Account ID Not Found in the System'],
    ['431', 'Tariff ID Must be Numeric'],
    ['432', 'Tariff ID Not Found in the System'],
    ['433', 'Destination Trunk Group ID Must be Numeric'],
    ['434', 'Destination Trunk Group ID Not Found in the System'],
    ['435', 'Call Surchage Must be Numeric and Maximum 2 Decimal Places'],
    ['436', 'BlockX Must be Numeric and Value Must be between 0 and 60'],
    ['437', 'Sub Account ID Not Belongs to the Customer ID'],
    ['440', 'User tied to the sub Account ID'],
    ['441', 'Customer is Not in ACTIVE status'],
    ['442', 'Customer is Not in SUSPEND status '],
    ['443', 'Customer is Not in SUSPEND or TERMINATED status'],
    ['444', 'Credit Must be Numeric and Maximum 2 Decimal Places'],
    ['445', 'API Topup is Restricted'],
    ['446', 'Customer Exipry Date Format Incorrect'],
    ['451', 'DID Number Must be Numeric '],
    ['452', 'DID Number too long'],
    ['453', 'Duplicated DID Number'],
    ['454', 'DID Number Not Found in the System'],
    ['500', 'Server/Database Error'],
    ['601', 'TB Operation Error'],
    ['602', 'TB Operation Timeout'],
    ['603', 'TB Operation Connection Refused'],
    ['604', 'TB Config Validation Fail'],
    ['605', 'TB Config Activation Fail'],
    ['611', 'TB Nap Too Long or Format Incorrect'],
    ['612', 'TB Nap Name Not Found in TB System'],
    ['613', 'Duplicated TB Nap Name'],
    ['614', 'Sip IP Address Format Incorrect'],
    ['615', 'Sip IP Port Must be Numeric '],
    ['616', 'Max simultaneous Calls Must be Numeric '],
    ['617', 'Max simultaneous Calls Out of the Possible Vale Range'],
    ['618', 'TB Route tied to the TB Nap'],
    ['619', 'Trunk tied to the TB Nap'],
    ['621', 'TB Route Name Too Long or Format Incorrect'],
    ['622', 'TB Route Name Not Found in TB System'],
    ['623', 'Duplicated TB Nap Name'],
  
  ])

